name: nodejs

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: webpage install, build, and test
        uses: actions/setup-node@v2.1.5
      - run: |
          npm install --global npm@7.6.1
          npm install
          npm run-script build
          npm run-script prod
